
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"

[[mods]] #mandatory
modId="lotsofberries" #mandatory
version="1.0" #mandatory
displayName="Lots of Berries" #mandatory
logoFile="examplemod.png"#optional
credits="HI!" #optional
authors="OhWhoah" #optional
description='''
A simple tutorial mod for minecraft 1.18
'''
