
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"

[[mods]] #mandatory
modId="tutorialmod" #mandatory
version="1.0" #mandatory
displayName="Tutorial Mod" #mandatory
logoFile="examplemod.png"#optional
credits="Thanks to everyone who installed this mod! Please do me a favour and leave a rating if you like it." #optional
authors="OhWhoah" #optional
description='''
A simple tutorial mod for minecraft 1.18
'''
